--[[
	© CloudSixteen.com do not share, re-distribute or modify
	without permission of its author (kurozael@gmail.com).
--]]

local FACTION = Clockwork.faction:New("Citizen");

FACTION.useFullName = true;
FACTION.material = "hl2rp2/factions/citizen";
FACTION.models = {
	female = {
	"models/humans/group01/female_01.mdl",
	"models/humans/group01/female_02.mdl",
	"models/humans/group01/female_03.mdl",
	"models/humans/group01/female_04.mdl",
	"models/humans/group01/female_06.mdl",
	"models/humans/group01/female_07.mdl",
	"models/humans/group01/female_20.mdl",
	"models/humans/group01/female_21.mdl",
	"models/humans/group01/female_22.mdl",
	"models/humans/group01/female_23.mdl",
	"models/humans/group01/female_24.mdl",
	"models/humans/group01/female_25.mdl",
	"models/humans/group01/female_26.mdl",
	"models/humans/group01/female_27.mdl",
	"models/barnes/refugee/female_28.mdl",
	"models/barnes/refugee/female_29.mdl",
	"models/barnes/refugee/female_30.mdl",
	"models/humans/group01/female_31.mdl",
	"models/humans/group01/female_32.mdl",
	"models/humans/group01/female_33.mdl",
	"models/humans/group01/female_34.mdl",
	"models/humans/group01/female_35.mdl",
	"models/humans/group01/female_36.mdl",
	"models/humans/group01/female_37.mdl",
	"models/humans/group01/female_38.mdl",
	"models/humans/group01/female_39.mdl",
	"models/humans/group01/female_40.mdl",
	"models/humans/group01/female_41.mdl",
	"models/humans/group01/female_42.mdl",
	"models/barnes/refugee/female_43.mdl",
	"models/humans/group01/female_44.mdl",
	"models/humans/group01/female_45.mdl",
	"models/humans/group01/female_46.mdl",
	"models/humans/group01/female_47.mdl",
	"models/humans/group01/female_48.mdl",
	"models/humans/group01/female_49.mdl",
	"models/humans/group01/female_53.mdl",
	"models/humans/group01/female_54.mdl",
	"models/humans/group01/female_55.mdl",
	"models/humans/group01/female_56.mdl",
	"models/humans/group01/female_57.mdl",
	"models/humans/group01/female_59.mdl",
	"models/humans/group01/female_60.mdl",
	"models/humans/group01/female_61.mdl",
	"models/humans/group01/female_62.mdl",
	"models/humans/group01/female_64.mdl",
	"models/humans/group01/female_65.mdl",
	"models/humans/group01/female_66.mdl",
	"models/humans/group01/female_67.mdl",
	"models/humans/group01/female_68.mdl",
	"models/humans/group01/female_69.mdl",
	"models/humans/group01/female_70.mdl",
	"models/humans/group01/female_71.mdl",
	"models/humans/group01/female_72.mdl",
	"models/humans/group01/female_73.mdl",
	"models/humans/group01/female_74.mdl",
	"models/humans/group01/female_75.mdl",
	"models/humans/group01/female_76.mdl",
	"models/humans/group01/female_77.mdl",
	"models/humans/group01/female_78.mdl",
	"models/humans/group01/female_79.mdl"
	},
	male = {
	"models/humans/group01/male_01.mdl",
	"models/humans/group01/male_02.mdl",
	"models/humans/group01/male_03.mdl",
	"models/humans/group01/male_04.mdl",
	"models/humans/group01/male_05.mdl",
	"models/humans/group01/male_06.mdl",
	"models/humans/group01/male_07.mdl",
	"models/humans/group01/male_08.mdl",
	"models/humans/group01/male_09.mdl",
	"models/humans/group01/male_10.mdl",
	"models/humans/group01/male_11.mdl",
	"models/humans/group01/male_12.mdl",
	"models/humans/group01/male_13.mdl",
	"models/humans/group01/male_14.mdl",
	"models/humans/group01/male_15.mdl",
	"models/humans/group01/male_16.mdl",
	"models/humans/group01/male_17.mdl",
	"models/humans/group01/male_18.mdl",
	"models/humans/group01/male_19.mdl",
	"models/humans/group01/male_20.mdl",
	"models/humans/group01/male_21.mdl",
	"models/humans/group01/male_22.mdl",
	"models/humans/group01/male_23.mdl",
	"models/humans/group01/male_24.mdl",
	"models/humans/group01/male_25.mdl",
	"models/humans/group01/male_26.mdl",
	"models/humans/group01/male_27.mdl",
	"models/humans/group01/male_28.mdl",
	"models/humans/group01/male_29.mdl",
	"models/humans/group01/male_30.mdl",
	"models/humans/group01/male_31.mdl",
	"models/humans/group01/male_33.mdl",
	"models/humans/group01/male_34.mdl",
	"models/humans/group01/male_35.mdl",
	"models/humans/group01/male_36.mdl",
	"models/humans/group01/male_37.mdl",
	"models/humans/group01/male_38.mdl",
	"models/humans/group01/male_39.mdl",
	"models/humans/group01/male_40.mdl",
	"models/humans/group01/male_41.mdl",
	"models/humans/group01/male_42.mdl",
	"models/humans/group01/male_43.mdl",
	"models/humans/group01/male_44.mdl",
	"models/humans/group01/male_45.mdl",
	"models/humans/group01/male_46.mdl",
	"models/humans/group01/male_47.mdl",
	"models/humans/group01/male_48.mdl",
	"models/humans/group01/male_49.mdl",
	"models/humans/group01/male_50.mdl",
	"models/humans/group01/male_51.mdl",
	"models/humans/group01/male_52.mdl",
	"models/humans/group01/male_53.mdl",
	"models/humans/group01/male_54.mdl",
	"models/humans/group01/male_55.mdl",
	"models/barnes/refugee/male_57.mdl",
	"models/barnes/refugee/male_58.mdl",
	"models/humans/group01/male_59.mdl",
	"models/humans/group01/male_60.mdl",
	"models/humans/group01/male_61.mdl",
	"models/humans/group01/male_62.mdl",
	"models/humans/group01/male_63.mdl",
	"models/humans/group01/male_64.mdl",
	"models/humans/group01/male_65.mdl",
	"models/humans/group01/male_66.mdl",
	"models/humans/group01/male_67.mdl",
	"models/humans/group01/male_68.mdl",
	"models/humans/group01/male_69.mdl",
	"models/humans/group01/male_70.mdl",
	"models/humans/group01/male_71.mdl",
	"models/humans/group01/male_72.mdl",
	"models/humans/group01/male_73.mdl",
	"models/humans/group01/male_74.mdl",
	"models/humans/group01/male_75.mdl",
	"models/humans/group01/male_76.mdl",
	"models/humans/group01/male_77.mdl",
	"models/humans/group01/male_78.mdl",
	"models/humans/group01/male_79.mdl",
	"models/humans/group01/male_80.mdl",
	"models/humans/group01/male_81.mdl",
	"models/humans/group01/male_82.mdl",
	"models/humans/group01/male_83.mdl",
	"models/humans/group01/male_84.mdl",
	"models/humans/group01/male_85.mdl",
	"models/humans/group01/male_86.mdl",
	"models/humans/group01/male_87.mdl",
	"models/humans/group01/male_88.mdl",
	"models/humans/group01/male_89.mdl",
	"models/humans/group01/male_90.mdl",
	"models/humans/group01/male_91.mdl",
	"models/humans/group01/male_92.mdl",
	"models/humans/group01/male_93.mdl",
	"models/humans/group01/male_94.mdl",
	"models/humans/group01/male_95.mdl",
	"models/humans/group01/male_96.mdl",
	"models/humans/group01/male_97.mdl",
	"models/humans/group01/male_100.mdl",
	"models/humans/group01/male_101.mdl",
	"models/humans/group01/male_102.mdl",
	"models/humans/group01/male_103.mdl",
	"models/humans/group01/male_104.mdl",
	"models/humans/group01/male_105.mdl",
	"models/humans/group01/male_106.mdl",
	"models/humans/group01/male_107.mdl",
	"models/humans/group01/male_108.mdl",
	"models/humans/group01/male_109.mdl",
	"models/humans/group01/male_110.mdl",
	"models/humans/group01/male_111.mdl",
	"models/humans/group01/male_112.mdl",
	"models/humans/group01/male_113.mdl",
	"models/humans/group01/male_114.mdl",
	"models/humans/group01/male_115.mdl",
	"models/humans/group01/male_116.mdl",
	"models/humans/group01/male_117.mdl",
	"models/humans/group01/male_118.mdl",
	"models/humans/group01/male_119.mdl",
	"models/humans/group01/male_120.mdl",
	"models/humans/group01/male_121.mdl",
	"models/humans/group01/male_122.mdl",
	"models/humans/group01/male_123.mdl",
	"models/humans/group01/male_124.mdl",
	"models/humans/group01/male_125.mdl",
	"models/humans/group01/male_126.mdl",
	"models/humans/group01/male_127.mdl",
	"models/humans/group01/male_128.mdl"
	};
};

-- Called when a player is transferred to the faction.
function FACTION:OnTransferred(player, faction, name)
	if (Schema:PlayerIsCombine(player)) then
		if (name) then
			local models = self.models[ string.lower(player:QueryCharacter("gender")) ];
			
			if (models) then
				player:SetCharacterData("model", models[ math.random(#models) ], true);
				
				Clockwork.player:SetName(player, name, true);
			end;
		else
			return false, "You need to specify a name as the third argument!";
		end;
	end;
end;

-- Checked for the custom ration plugin
FACTION.canGetRations = true;
FACTION.noIDCard = true;
FACTION.canUseRationToken = true;
FACTION.rationUniqueID = "civilian_grade_ration";

FACTION_CITIZEN = FACTION:Register();